analysis:
  target_date: "2024-11-04"
  price_change_threshold: 5.0  # Процентное изменение цены для определения значимого изменения
  analysis_window_days: 7      # Количество дней до и после целевой даты для анализа

logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"
  file: "market_analysis.log" 